# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cBlog
email: ctefer@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>cTefer's Blog!</h3><h1>DevJournal</h1>"



baseurl: "/cBlog" # the subpath of your site, e.g. /blog
url: "http://ctefer.github.io" # the base hostname & protocol for your site
github_username: ctefer

# Build settings
markdown: kramdown
